### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [A-tG/mpv.net-ScriptsExtension#1]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by A-tG** [comment]
This is [mpv.net ](https://github.com/stax76/mpv.net) script not mpv
